# Generated by Django 4.1.4 on 2022-12-31 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dot_learn_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question_var",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="created",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="category",
            name="answer_var",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="subject_var",
        ),
        migrations.RemoveField(
            model_name="question",
            name="topic_var",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="branch_var",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="chapter_var",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.question",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="answer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.question",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="subject",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.topic",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="branch",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.branch",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="branch",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.branch",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="chapter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.chapter",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.subject",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
