# Generated by Django 4.1.4 on 2023-01-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dot_learn_app",
            "0002_remove_answer_question_var_remove_branch_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="branch_related",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="topic",
            name="branch",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.branch",
            ),
        ),
    ]
