# Generated by Django 4.1.4 on 2023-01-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dot_learn_app", "0003_category_branch_related_alter_topic_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="branch_related",
        ),
        migrations.AddField(
            model_name="category",
            name="branch_rel",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
