# Generated by Django 4.1.4 on 2023-01-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dot_learn_app", "0004_remove_category_branch_related_category_branch_rel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="branch_rel",
            new_name="branch_related",
        ),
    ]
