# Generated by Django 4.1.4 on 2023-01-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dot_learn_app", "0005_rename_branch_rel_category_branch_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="branch_related",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dot_learn_app.branch",
            ),
        ),
    ]
