# Generated by Django 4.1.4 on 2023-01-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dot_learn_app", "0006_alter_category_branch_related"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="answer",
            new_name="question",
        ),
    ]
